/**
 * build.ts — EIP-8244 codegen.
 *
 * Reads html/index.html, minifies it, gzips it, base64-encodes the result, and
 * generates contracts/HelloWorldFrontend.sol with the compressed payload baked
 * into the constructor as a data contract (SSTORE2-style, like TamaSwap).
 *
 * Run: node scripts/build.ts
 */
import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HTML_PATH = join(ROOT, "html", "index.html");
const OUT_PATH = join(ROOT, "contracts", "HelloWorldFrontend.sol");

// EIP-170 runtime code size cap for the data contract.
const CODE_SIZE_LIMIT = 24576;

/** Conservative minify: drop whitespace between tags and trim. Safe for this POC. */
function minify(html: string): string {
  return html
    .replace(/>\s+</g, "><")
    .replace(/^\s+|\s+$/g, "");
}

function toHex(buf: Buffer | Uint8Array): string {
  return Buffer.from(buf).toString("hex");
}

function generateContract(payloadHex: string): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @title HelloWorldFrontend
/// @notice EIP-8244 contract-hosted application HTML. Generated by scripts/build.ts.
/// @dev The HTML document is minified, gzipped and base64-encoded at build time and
///      stored as the runtime code of a data contract. \`html()\` returns a small
///      bootstrap document that inflates the payload in the browser via
///      DecompressionStream("gzip"). Do not edit by hand; edit html/index.html instead.
contract HelloWorldFrontend {
    /// @notice Data contract holding the gzip+base64 HTML payload as runtime code.
    address public immutable HTML_DATA;

    /// @notice HTTP-style response header key/value pair (ERC-5219).
    struct KeyValue {
        string key;
        string value;
    }

    /// @notice Deploys the compressed HTML payload into a data contract.
    constructor() payable {
        HTML_DATA = _deployData(hex"${payloadHex}");
    }

    /// @notice Returns the complete bootstrapping HTML document (EIP-8244).
    /// @return The self-decompressing HTML document as a string.
    function html() external view returns (string memory) {
        return string.concat(
            "<!doctype html><meta charset=\\"utf-8\\"><meta name=\\"viewport\\" content=\\"width=device-width,initial-scale=1\\"><title>Onchain App</title><script>(async()=>{const B=\\"",
            _readData(HTML_DATA),
            "\\";try{let u=Uint8Array.from(atob(B),c=>c.charCodeAt()),h=await new Response(new Blob([u]).stream().pipeThrough(new DecompressionStream(\\"gzip\\"))).text(),d=new DOMParser().parseFromString(h,\\"text/html\\"),im=n=>document.importNode(n,true);document.head.replaceChildren(...[...d.head.childNodes].map(im));document.body.replaceChildren(...[...d.body.childNodes].map(im));for(let o of [...document.scripts]){let s=document.createElement(\\"script\\");for(let a of o.attributes)s.setAttribute(a.name,a.value);s.text=o.textContent;o.replaceWith(s)}}catch{document.body.textContent=\\"Load failed\\"}})()</script>"
        );
    }

    /// @notice ERC-5219 resolver mode identifier, for ERC-4804 (web3://) clients.
    function resolveMode() external pure returns (bytes32) {
        return "5219";
    }

    /// @notice Serves the document via ERC-5219 resource requests.
    /// @param resource Requested path segments.
    /// @return statusCode HTTP-style status code.
    /// @return body Response body.
    /// @return headers HTTP-style response headers.
    function request(string[] memory resource, KeyValue[] memory)
        external
        view
        returns (uint16 statusCode, string memory body, KeyValue[] memory headers)
    {
        if (!_isIndexResource(resource)) {
            headers = new KeyValue[](1);
            headers[0] = KeyValue("Content-Type", "text/plain; charset=utf-8");
            return (404, "Not found", headers);
        }
        headers = new KeyValue[](2);
        headers[0] = KeyValue("Content-Type", "text/html; charset=utf-8");
        headers[1] = KeyValue("Cache-Control", "public, max-age=31536000, immutable");
        return (200, this.html(), headers);
    }

    /// @notice Whether a resource path should resolve to the index document.
    function _isIndexResource(string[] memory resource) private pure returns (bool) {
        if (resource.length == 0) return true;
        if (resource.length == 1) {
            bytes32 v = keccak256(bytes(resource[0]));
            return v == keccak256(bytes("")) || v == keccak256(bytes("/"))
                || v == keccak256(bytes("index.html"));
        }
        return false;
    }

    /// @notice Deploys a byte payload as contract code and returns its address.
    function _deployData(bytes memory payload) private returns (address d) {
        require(payload.length <= 0xFFFF, "payload too big");
        bytes memory initcode =
            bytes.concat(hex"61", bytes2(uint16(payload.length)), hex"80600a5f395ff3", payload);
        assembly ("memory-safe") {
            d := create(0, add(initcode, 0x20), mload(initcode))
        }
        require(d != address(0), "deploy failed");
    }

    /// @notice Reads all runtime code bytes from a data contract as a string.
    function _readData(address d) private view returns (string memory s) {
        assembly ("memory-safe") {
            let sz := extcodesize(d)
            s := mload(0x40)
            mstore(s, sz)
            let ptr := add(s, 0x20)
            extcodecopy(d, ptr, 0, sz)
            let padded := and(add(sz, 0x1f), not(0x1f))
            mstore(add(ptr, padded), 0)
            mstore(0x40, add(add(ptr, padded), 0x20))
        }
    }
}
`;
}

const rawHtml = readFileSync(HTML_PATH, "utf8");
const minified = minify(rawHtml);
const gzipped = gzipSync(Buffer.from(minified, "utf8"), { level: 9 });
const base64 = gzipped.toString("base64");
const payloadHex = toHex(Buffer.from(base64, "utf8"));

writeFileSync(OUT_PATH, generateContract(payloadHex), "utf8");

const rawBytes = Buffer.byteLength(rawHtml, "utf8");
const minBytes = Buffer.byteLength(minified, "utf8");
const b64Bytes = Buffer.byteLength(base64, "utf8");
const pct = (n: number) => `${((n / rawBytes) * 100).toFixed(1)}%`;

console.log("EIP-8244 build report");
console.log(`  raw HTML        ${rawBytes} bytes`);
console.log(`  minified        ${minBytes} bytes (${pct(minBytes)})`);
console.log(`  gzip            ${gzipped.length} bytes (${pct(gzipped.length)})`);
console.log(`  gzip+base64     ${b64Bytes} bytes (${pct(b64Bytes)}) [stored on-chain]`);
console.log(`  -> ${OUT_PATH}`);

if (b64Bytes > CODE_SIZE_LIMIT) {
  console.warn(
    `\n  WARNING: payload (${b64Bytes} bytes) exceeds the ${CODE_SIZE_LIMIT}-byte ` +
      `EIP-170 data-contract limit. Deployment will fail. ` +
      `Split the payload across multiple data contracts.`,
  );
}
